receivers:
  filelog:
    include: [/var/lib/docker/containers/*/*-json.log]
    poll_interval: 200ms
    start_at: end
    include_file_name: false
    include_file_path: false
    operators:
      - id: container-parser
        type: container
        format: docker

processors:
  batch:

exporters:
  otlp:
    endpoint: "tone.i.nokiy.net:4317"
    tls:
      insecure: true

service:
  telemetry:
    metrics:
      level: none
  pipelines:
    logs:
      receivers: [filelog]
      processors: [batch]
      exporters: [otlp]
